M48
; DRILL file {KiCad 8.0.0} date 2024-03-20T19:05:42-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-20T19:05:42-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.1587Y-2.936
X5.1587Y-3.127
T2
X5.0394Y-2.9242
X5.0394Y-3.1388
M30
